import { useEffect, useMemo, useState } from 'react';
import { EJourneyStage } from '../../../@business/enum/EJourneyStage';
import { ContestJsonImport } from './ContestJsonImport';
import { ContestSubjectEditor } from './ContestSubjectEditor';
import { ContestConfirmationDetails } from './ContestConfirmationDetails';
import type { JourneySummaryResponse } from '../../../@business/dto/response/journey.response';
import type { SaveJourneyStructureRequest } from '../../../@business/dto/request/journey.request';
import { getRequestErrorMessage } from '../../utils/getRequestErrorMessage';
import { journeyService } from '../../../@business/service/Journey.service';

export type Subject = { name:string; topics:{name:string;subtopics:string[]}[] };
function mergeSubjects(current:Subject[], imported:Subject[]){const merged=current.map(subject=>({...subject,topics:subject.topics.map(topic=>({...topic,subtopics:[...topic.subtopics]}))}));for(const incoming of imported){const subject=merged.find(item=>item.name.toLocaleLowerCase()===incoming.name.toLocaleLowerCase());if(!subject){merged.push(incoming);continue}for(const incomingTopic of incoming.topics){const topic=subject.topics.find(item=>item.name.toLocaleLowerCase()===incomingTopic.name.toLocaleLowerCase());if(!topic){subject.topics.push(incomingTopic);continue}const names=new Set(topic.subtopics.map(item=>item.toLocaleLowerCase()));topic.subtopics.push(...incomingTopic.subtopics.filter(item=>!names.has(item.toLocaleLowerCase())))}}return merged}
type Props = { open:boolean; onClose():void; onCreate(request:SaveJourneyStructureRequest):Promise<number>; initialData?:JourneySummaryResponse|null; onSave?(request:SaveJourneyStructureRequest):Promise<void> };

export function ContestCreationDrawer({open,onClose,onCreate,initialData,onSave}:Props){
  const editing=Boolean(initialData);
  const[step,setStep]=useState(editing?2:1);const[kind,setKind]=useState<'future'|'completed'>(initialData?.stage===EJourneyStage.Completed?'completed':'future');const[title,setTitle]=useState(initialData?.title??'');const[institution,setInstitution]=useState(initialData?.institution??'');const[board,setBoard]=useState('');const[position,setPosition]=useState(initialData?.position??'');const[openings,setOpenings]=useState('');const[stage,setStage]=useState(initialData?.stage===EJourneyStage.PostNotice?EJourneyStage.PostNotice:EJourneyStage.PreNotice);const[date,setDate]=useState(initialData?.examDate??'');const[image,setImage]=useState(initialData?.logoUrl??'');const[subjectName,setSubjectName]=useState('');const[subjects,setSubjects]=useState<Subject[]>([]);const[error,setError]=useState('');
  const steps=kind==='completed'?['Situação','Dados','Conteúdo','Confirmar']:['Situação','Dados','Planejamento','Conteúdo','Confirmar'];const visualStep=kind==='completed'&&step>=4?step-1:step;
  const initials=useMemo(()=>title.trim().slice(0,2).toUpperCase()||'SC',[title]);
  const topicCount=subjects.reduce((total,subject)=>total+subject.topics.length,0);const subtopicCount=subjects.reduce((total,subject)=>total+subject.topics.reduce((sum,topic)=>sum+topic.subtopics.length,0),0);
  const[dashboardOpen,setDashboardOpen]=useState(false);const[saving,setSaving]=useState(false);
  useEffect(()=>{if(!open||!initialData)return;let active=true;journeyService.findById(initialData.id).then(details=>{if(!active)return;setTitle(details.title);setInstitution(details.institution??'');setBoard(details.examBoard??'');setPosition(details.position??'');setOpenings(details.openings?.toString()??'');setStage(details.stage===EJourneyStage.PostNotice?EJourneyStage.PostNotice:EJourneyStage.PreNotice);setDate(details.examDate??'');setImage(details.logoUrl??'');setSubjects([...details.knowledgeAreas].sort((a,b)=>a.order-b.order).map(area=>({name:area.title,topics:[...area.nodes].sort((a,b)=>a.order-b.order).map(node=>({name:node.title,subtopics:[...node.children].sort((a,b)=>a.order-b.order).map(child=>child.title)}))})));}).catch(requestError=>{if(active)setError(getRequestErrorMessage(requestError,'Não foi possível carregar o conteúdo do concurso.'))});return()=>{active=false}},[open,initialData?.id]);
  function next(){setError('');if(step===1){setStep(2);return}if(step===2&&!title.trim()){setError('Informe o nome do concurso.');return}if(step===2&&kind==='completed'){setStep(4);return}if(step===3&&stage===EJourneyStage.PostNotice&&!date){setError('Informe a data da prova.');return}setStep(current=>Math.min(5,current+1))}
  function previous(){setError('');setStep(current=>kind==='completed'&&current===4?2:Math.max(1,current-1))}
  function chooseImage(file?:File){if(!file)return;if(file.size>2*1024*1024){setError('Escolha uma imagem de até 2 MB.');return}const reader=new FileReader();reader.onload=()=>setImage(String(reader.result));reader.readAsDataURL(file)}
  function addSubject(){const name=subjectName.trim();if(!name||subjects.some(item=>item.name.toLowerCase()===name.toLowerCase()))return;setSubjects(current=>[...current,{name,topics:[]}]);setSubjectName('')}
  async function finish(){
    if(saving)return;
    const numericOpenings=openings.match(/\d+/)?.[0];
    const request:SaveJourneyStructureRequest={
      journey:{id:initialData?.id??null,title:title.trim(),institution:institution.trim()||null,examBoard:board.trim()||null,position:position.trim()||null,salary:null,openings:numericOpenings?Number(numericOpenings):null,noticeUrl:null,examDate:kind==='future'&&stage===EJourneyStage.PostNotice?date:null,stage:kind==='completed'?EJourneyStage.Completed:stage,includeInStatistics:true,logoUrl:image||null},
      knowledgeAreas:subjects.map((subject,areaOrder)=>({title:subject.name,order:areaOrder,nodes:subject.topics.map((topic,topicOrder)=>({title:topic.name,order:topicOrder,children:topic.subtopics.map((subtopic,subtopicOrder)=>({title:subtopic,order:subtopicOrder,children:[]}))}))}))
    };
    setSaving(true);setError('');
    try{if(editing&&onSave){await onSave(request);onClose()}else{await onCreate(request)}}catch(requestError){setError(getRequestErrorMessage(requestError,'Não foi possível salvar o concurso.'))}finally{setSaving(false)}
  }
  if(!open)return null;
  if(dashboardOpen)return <main className="contest-dashboard-preview"><aside><div className="dashboard-brand"><span>S</span><strong>Kurumí</strong></div><button className="active">⌂ <span>Visão geral</span></button><button>◷ <span>Plano de estudos</span></button><button>✓ <span>Revisões</span></button><button>▤ <span>Simulados</span></button><button>◎ <span>Desempenho</span></button><div className="dashboard-contest-mini">{image?<img src={image} alt=""/>:<span>{initials}</span>}<div><strong>{title}</strong><small>{institution||'Concurso'}</small></div></div></aside><section><header><div><span className="eyebrow">VISÃO GERAL</span><h1>{title}</h1><p>{kind==='completed'?'Concurso realizado':stage===EJourneyStage.PreNotice?'Preparação pré-edital':`Prova em ${date.split('-').reverse().join('/')}`}</p></div><button onClick={()=>{setDashboardOpen(false);onClose()}}>Voltar aos concursos</button></header><div className="dashboard-metrics"><article><span>◷</span><strong>0h</strong><small>tempo estudado</small></article><article><span>✓</span><strong>0</strong><small>questões resolvidas</small></article><article><span>◎</span><strong>—</strong><small>taxa de acertos</small></article><article><span>▤</span><strong>{subjects.length}</strong><small>disciplinas</small></article></div><div className="dashboard-grid"><section className="dashboard-subjects"><header><div><h2>Disciplinas</h2><p>Seu conteúdo inicial</p></div><button>＋ Adicionar</button></header>{subjects.length?subjects.map((subject,index)=><article key={subject.name}><span>{String(index+1).padStart(2,'0')}</span><strong>{subject.name}</strong><small>0% concluído</small><i><b style={{width:'0%'}}/></i><button>›</button></article>):<div className="dashboard-empty"><span>▤</span><h3>Nenhuma disciplina adicionada</h3><p>Comece montando o conteúdo do concurso.</p></div>}</section><aside className="dashboard-today"><span className="eyebrow">HOJE</span><h2>Próximo passo</h2><p>{subjects.length?'Escolha uma disciplina e inicie sua primeira sessão de estudo.':'Adicione as disciplinas do edital para montar seu plano.'}</p><button className="filled-button">{subjects.length?'Começar a estudar':'Adicionar disciplina'}</button><div><strong>Seu progresso começa aqui</strong><small>As métricas serão preenchidas conforme você estudar.</small></div></aside></div></section></main>;
  return <div className="contest-drawer-backdrop" onMouseDown={onClose}><aside className="contest-creation-drawer" onMouseDown={event=>event.stopPropagation()}><header className="contest-drawer-header"><div><span className="eyebrow">{editing?'EDITAR CONCURSO':'NOVO CONCURSO'}</span><h2>{steps[visualStep-1]}</h2></div><button onClick={onClose} aria-label="Fechar">×</button></header><div className="contest-stepper">{steps.map((label,index)=><div className={visualStep===index+1?'active':visualStep>index+1?'done':''} key={label}><span>{visualStep>index+1?'✓':index+1}</span><small>{label}</small></div>)}</div><div className="contest-drawer-body"><section className="contest-form-stage">
  {step===1&&<><h3>Qual concurso você quer cadastrar?</h3><p>Escolha a situação atual para mostrarmos apenas as próximas etapas necessárias.</p><div className="contest-kind-grid"><button className={kind==='future'?'selected':''} onClick={()=>setKind('future')}><span>◎</span><strong>Concurso a realizar</strong><small>Estou estudando ou aguardando o edital.</small></button><button className={kind==='completed'?'selected':''} onClick={()=>setKind('completed')}><span>✓</span><strong>Concurso realizado</strong><small>A prova já aconteceu e quero registrar o histórico.</small></button></div></>}
  {step===2&&<><h3>Informações do concurso</h3><p>Preencha o que você souber. Os dados atualizam o card ao lado.</p><div className="contest-fields"><label className="wide"><span>Nome do concurso *</span><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Ex.: Auditor TCU"/></label><label><span>Órgão</span><input value={institution} onChange={e=>setInstitution(e.target.value)} placeholder="Tribunal de Contas"/></label><label><span>Banca</span><input value={board} onChange={e=>setBoard(e.target.value)} placeholder="Cebraspe"/></label><label><span>Cargo ou área</span><input value={position} onChange={e=>setPosition(e.target.value)} placeholder="Auditor Federal"/></label><label><span>Vagas</span><input value={openings} onChange={e=>setOpenings(e.target.value)} placeholder="20 imediatas + CR"/></label><label className="wide image-field"><span>Foto ou logotipo</span><div>{image?<img src={image} alt="Prévia"/>:<span className="image-placeholder">▧</span>}<label className="image-button">Escolher imagem<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>chooseImage(e.target.files?.[0])}/></label>{image&&<button onClick={()=>setImage('')}>Remover</button>}</div></label></div></>}
  {step===3&&<><h3>Planejamento da prova</h3><p>A data aparece somente quando o edital já foi publicado.</p><div className="planning-options"><button className={stage===EJourneyStage.PreNotice?'selected':''} onClick={()=>{setStage(EJourneyStage.PreNotice);setDate('')}}><strong>Pré-edital</strong><small>Ainda não existe uma data oficial.</small></button><button className={stage===EJourneyStage.PostNotice?'selected':''} onClick={()=>setStage(EJourneyStage.PostNotice)}><strong>Pós-edital</strong><small>O edital e a data já foram publicados.</small></button></div>{stage===EJourneyStage.PostNotice&&<label className="drawer-date"><span>Data da prova</span><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label>}</>}
  {step===4&&<><h3>Conteúdo do concurso</h3><p>Monte uma prévia das disciplinas. A importação completa será ligada ao backend depois.</p><div className="quick-subject"><input value={subjectName} onChange={e=>setSubjectName(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();addSubject()}}} placeholder="Nome da disciplina"/><button onClick={addSubject}>＋</button></div><div className="quick-subject-list">{subjects.map((subject,index)=><div key={subject.name}><span>{String(index+1).padStart(2,'0')}</span><strong>{subject.name}</strong><button onClick={()=>setSubjects(current=>current.filter((_,i)=>i!==index))}>×</button></div>)}{!subjects.length&&<p>Nenhuma disciplina adicionada.</p>}</div></>}
  {step===5&&<><h3>Confira antes de continuar</h3><p>Revise as informações que serão usadas para montar o dashboard do concurso.</p><div className="contest-summary"><div className="summary-title"><strong>{title}</strong><small>{institution||'Órgão não informado'} · {position||'Cargo não informado'}</small></div><div className="summary-content-counts"><article><strong>{subjects.length}</strong><small>Disciplinas</small></article><article><strong>{topicCount}</strong><small>Tópicos</small></article><article><strong>{subtopicCount}</strong><small>Subtópicos</small></article></div><dl><div><dt>Situação</dt><dd>{kind==='completed'?'Concurso realizado':'Concurso a realizar'}</dd></div><div><dt>Planejamento</dt><dd>{kind==='completed'?'Prova realizada':stage===EJourneyStage.PreNotice?'Pré-edital':'Pós-edital'}</dd></div><div><dt>Banca</dt><dd>{board||'Não informada'}</dd></div><div><dt>Vagas</dt><dd>{openings||'Não informado'}</dd></div>{kind==='future'&&stage===EJourneyStage.PostNotice&&<div><dt>Data da prova</dt><dd>{date?date.split('-').reverse().join('/'):'Não informada'}</dd></div>}</dl>{subjects.length>0&&<div className="summary-subjects"><span>Conteúdo cadastrado</span><div>{subjects.slice(0,6).map(subject=><small key={subject.name}>{subject.name}</small>)}{subjects.length>6&&<small>+{subjects.length-6}</small>}</div></div>}</div></>}
  {step===5&&<ContestConfirmationDetails subjects={subjects}/>} {step===4&&<><ContestJsonImport onImport={imported=>setSubjects(current=>mergeSubjects(current,imported))}/><ContestSubjectEditor subjects={subjects} onChange={setSubjects}/></>} {error&&<div className="wizard-error">{error}</div>}</section><aside className="contest-live-preview"><span className="eyebrow">PRÉVIA DO CONCURSO</span><div className="preview-cover">{image?<img src={image} alt="Concurso"/>:<span>{initials}</span>}</div><span className="preview-status">{kind==='completed'?'REALIZADO':stage===EJourneyStage.PreNotice?'PRÉ-EDITAL':'PÓS-EDITAL'}</span><h3>{title||'Nome do concurso'}</h3><p>{institution||'Órgão ainda não informado'}</p><dl><div><dt>Cargo</dt><dd>{position||'—'}</dd></div><div><dt>Banca</dt><dd>{board||'—'}</dd></div><div><dt>Vagas</dt><dd>{openings||'—'}</dd></div><div><dt>Conteúdo</dt><dd>{subjects.length} disciplinas · {topicCount} tópicos</dd></div>{kind==='future'&&stage===EJourneyStage.PostNotice&&<div><dt>Prova</dt><dd>{date?date.split('-').reverse().join('/'):'—'}</dd></div>}</dl></aside></div><footer className="contest-drawer-actions">{step>1&&<button onClick={previous}>Voltar</button>}<button className="filled-button" onClick={step===5?finish:next}>{step===5?(editing?'Salvar alterações':'Visualizar dashboard'):'Continuar'}</button></footer></aside></div>
}
