import { useState } from 'react';
import type { Subject } from './ContestCreationDrawer';

type Props = { subjects: Subject[]; onChange(value: Subject[]): void };
const Chevron = ({ open }: { open: boolean }) => <svg className={open ? 'open' : ''} viewBox="0 0 24 24"><path d="m9 6 6 6-6 6"/></svg>;

export function ContestSubjectEditor({ subjects, onChange }: Props) {
  const [area, setArea] = useState<number | null>(null);
  const [topic, setTopic] = useState<string | null>(null);
  const [drafts, setDrafts] = useState<Record<string, string>>({});
  const setDraft = (key: string, value: string) => setDrafts(current => ({ ...current, [key]: value }));
  const addTopic = (areaIndex: number) => { const key = `t-${areaIndex}`, name = drafts[key]?.trim(); if (!name) return; onChange(subjects.map((subject, index) => index === areaIndex ? { ...subject, topics: [...subject.topics, { name: name.slice(0, 300), subtopics: [] }] } : subject)); setDraft(key, ''); setArea(areaIndex); };
  const addSubtopic = (areaIndex: number, topicIndex: number) => { const key = `s-${areaIndex}-${topicIndex}`, name = drafts[key]?.trim(); if (!name) return; onChange(subjects.map((subject, index) => index !== areaIndex ? subject : { ...subject, topics: subject.topics.map((item, current) => current === topicIndex ? { ...item, subtopics: [...item.subtopics, name.slice(0, 300)] } : item) })); setDraft(key, ''); setTopic(`${areaIndex}-${topicIndex}`); };
  const removeSubject = (areaIndex: number) => { onChange(subjects.filter((_, index) => index !== areaIndex)); setArea(null); setTopic(null); };
  const removeTopic = (areaIndex: number, topicIndex: number) => onChange(subjects.map((subject, index) => index === areaIndex ? { ...subject, topics: subject.topics.filter((_, current) => current !== topicIndex) } : subject));
  const removeSubtopic = (areaIndex: number, topicIndex: number, subtopicIndex: number) => onChange(subjects.map((subject, index) => index !== areaIndex ? subject : { ...subject, topics: subject.topics.map((item, current) => current === topicIndex ? { ...item, subtopics: item.subtopics.filter((_, subIndex) => subIndex !== subtopicIndex) } : item) }));

  return <section className="contest-subject-tree"><header><div><strong>Conteúdo cadastrado</strong><small>Clique para visualizar, complementar ou remover itens.</small></div><span>{subjects.length}</span></header>{subjects.map((subject, areaIndex) => { const opened = area === areaIndex; return <article key={`${subject.name}-${areaIndex}`}><div className="subject-row"><button onClick={() => { setArea(opened ? null : areaIndex); setTopic(null); }}><span className="subject-icon">▤</span><div><strong>{subject.name}</strong><small>{subject.topics.length} tópicos</small></div><span className="chevron"><Chevron open={opened}/></span></button><button className="tree-remove" onClick={() => removeSubject(areaIndex)} aria-label={`Remover ${subject.name}`}>×</button></div>{opened && <div className="subject-content"><div className="inline-node-add"><input maxLength={300} value={drafts[`t-${areaIndex}`] || ''} onChange={event => setDraft(`t-${areaIndex}`, event.target.value)} placeholder="Adicionar tópico"/><button onClick={() => addTopic(areaIndex)}>＋</button></div>{subject.topics.map((item, topicIndex) => { const key = `${areaIndex}-${topicIndex}`, topicOpen = topic === key; return <div className="topic-node" key={key}><div className="topic-node-row"><button onClick={() => setTopic(topicOpen ? null : key)}><span className="topic-icon">●</span><strong>{item.name}</strong><small>{item.subtopics.length}</small><span className="chevron"><Chevron open={topicOpen}/></span></button><button className="tree-remove" onClick={() => removeTopic(areaIndex, topicIndex)} aria-label={`Remover ${item.name}`}>×</button></div>{topicOpen && <div className="subtopic-panel"><ul>{item.subtopics.map((subtopic, subtopicIndex) => <li key={`${subtopic}-${subtopicIndex}`}><span>↳</span>{subtopic}<button className="tree-remove" onClick={() => removeSubtopic(areaIndex, topicIndex, subtopicIndex)} aria-label={`Remover ${subtopic}`}>×</button></li>)}</ul><div className="inline-node-add"><input maxLength={300} value={drafts[`s-${areaIndex}-${topicIndex}`] || ''} onChange={event => setDraft(`s-${areaIndex}-${topicIndex}`, event.target.value)} placeholder="Adicionar subtópico"/><button onClick={() => addSubtopic(areaIndex, topicIndex)}>＋</button></div></div>}</div>; })}</div>}</article>; })}</section>;
}
