export const adminUsersTokens = {
  page: 'flex min-h-screen flex-col bg-[var(--md-sys-color-surface)]', badge: 'ml-[-4px] mr-1 self-center rounded bg-[var(--md-sys-color-primary)] px-2 py-0.5 text-[.65rem] font-bold uppercase tracking-[.08em] text-[var(--md-sys-color-on-primary)]',
  content: 'mx-auto w-full max-w-[1100px] flex-1 px-6 pb-16 pt-8', header: 'mb-8', eyebrow: 'text-[11px] font-extrabold tracking-[.12em] text-[var(--md-sys-color-primary)]', heading: 'mb-2 mt-1 text-[1.75rem] font-bold text-[var(--md-sys-color-on-surface)]', subtitle: 'm-0 text-sm text-[var(--md-sys-color-on-surface-variant)]',
  section: 'overflow-hidden rounded-xl border border-[var(--md-sys-color-outline-variant)] bg-[var(--md-sys-color-surface-bright)]', toolbar: 'flex items-center gap-4 border-b border-[var(--md-sys-color-outline-variant)] px-5 py-4', searchWrap: 'relative flex flex-1 items-center', searchIcon: 'pointer-events-none absolute left-3 h-4 w-4 text-[var(--md-sys-color-outline)]', search: 'w-full rounded-lg border border-[var(--md-sys-color-outline-variant)] bg-[var(--md-sys-color-surface)] py-2 pl-9 pr-3 text-sm text-[var(--md-sys-color-on-surface)] outline-none placeholder:text-[var(--md-sys-color-outline)] focus:border-[var(--md-sys-color-primary)]', count: 'whitespace-nowrap text-xs text-[var(--md-sys-color-on-surface-variant)]',
  empty: 'flex flex-col items-center gap-2 px-6 py-12 text-center text-[var(--md-sys-color-on-surface-variant)]', emptyIcon: 'text-3xl opacity-40', emptyTitle: 'text-base text-[var(--md-sys-color-on-surface)]', emptyText: 'm-0 text-sm',
  tableWrap: 'overflow-x-auto', table: 'w-full border-collapse text-sm', tableHeadRow: 'border-b border-[var(--md-sys-color-outline-variant)]', th: 'px-4 py-3 text-left text-xs font-semibold uppercase tracking-[.05em] text-[var(--md-sys-color-on-surface-variant)]', row: 'hover:bg-[var(--md-sys-color-surface-container)]', inactiveRow: 'opacity-60', td: 'border-b border-[var(--md-sys-color-outline-variant)] px-4 py-3.5 align-middle text-[var(--md-sys-color-on-surface)] last:border-b-0', name: 'font-medium', noName: 'font-normal italic text-[var(--md-sys-color-on-surface-variant)]', email: 'text-[var(--md-sys-color-on-surface-variant)]', date: 'whitespace-nowrap text-xs text-[var(--md-sys-color-on-surface-variant)]', roles: 'flex flex-wrap gap-1', action: 'text-right',
  status: 'inline-flex items-center gap-1.5 rounded-full px-2.5 py-[3px] text-xs font-semibold before:h-1.5 before:w-1.5 before:rounded-full before:bg-current', statusActive: 'bg-[#4ade801a] text-[#25844a]', statusInactive: 'bg-[#94a3b81a] text-[#64748b]', role: 'rounded bg-[var(--md-sys-color-primary-container)] px-2 py-0.5 text-[.7rem] font-semibold tracking-[.03em] text-[var(--md-sys-color-on-primary-container)]',
  actionButton: 'whitespace-nowrap rounded-md border px-3.5 py-1.5 text-xs font-semibold transition', dangerButton: 'border-[#ef444433] bg-[#ef44441a] text-[#c53e3e] hover:bg-[#ef444433]', primaryButton: 'border-[#4ade8033] bg-[#4ade801a] text-[#25844a] hover:bg-[#4ade8033]',
} as const;
