import type { StudyRoutineRegisterRequest, StudyRoutineUpdateRequest } from '../dto/request/studyRoutine.request';
import type { StudyRoutineResponse } from '../dto/response/studyRoutine.response';
import { HttpMethod } from '../enum/httpMethod.enum';
import { clientRequest } from './base/httpHandler.service';
const findAll = (journeyId: number) => clientRequest<StudyRoutineResponse[]>({ url: '/StudyRoutine/list', method: HttpMethod.Get, axiosConfig: { params: { journeyId } } });
const register = (body: StudyRoutineRegisterRequest) => clientRequest<StudyRoutineResponse>({ url: '/StudyRoutine/register', method: HttpMethod.Post, body });
const update = (body: StudyRoutineUpdateRequest) => clientRequest<StudyRoutineResponse>({ url: '/StudyRoutine/update', method: HttpMethod.Put, body });
export type StudyRoutineBlockResponse = { id: number; syllabusNodeId: number; scheduledFor: string; type: number; status: number; plannedMinutes: number; completedMinutes: number; order: number };
const generate = (studyRoutineId: number, journeyId: number) => clientRequest<StudyRoutineBlockResponse[]>({ url: '/StudyRoutine/generate', method: HttpMethod.Post, body: { studyRoutineId, journeyId } });
const blocks = (studyRoutineId: number, from: string, to: string) => clientRequest<StudyRoutineBlockResponse[]>({ url: '/StudyRoutine/blocks', method: HttpMethod.Get, axiosConfig: { params: { routineId: studyRoutineId, from, to } } });
const complete = (body: { blockId: number; completed: boolean; completedMinutes: number; scheduleReview: boolean; reviewDate?: string | null; clearPending?: boolean }) => clientRequest<StudyRoutineBlockResponse>({ url: '/StudyRoutine/blocks/complete', method: HttpMethod.Put, body });
export const studyRoutineService = { findAll, register, update, generate, blocks, complete };
